{% set name = "conda_subprocess" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/conda_subprocess-{{ version }}.tar.gz
  sha256: f8a3a811f45b13aecfea054ca6c11c4c8e4a751be44bcc823537889c749a8ec9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9
    - conda
    - versioneer
    - pip
  run:
    - python >=3.9
    - conda >=22.9.0,<=23.11.0

test:
  imports:
    - conda_subprocess
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Run a subprocess in a different conda environment.
  home: https://github.com/pyiron/conda_subprocess
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
