{% set name = "conda_subprocess" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/conda_subprocess-{{ version }}.tar.gz
  sha256: 3e7da7604797ddef8cf773f97f0e9815b23d5718decb759999784d15c80e6dc2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - conda
    - versioneer
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - conda >=22.9.0,<=24.7.1

test:
  imports:
    - conda_subprocess
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Run a subprocess in a different conda environment.
  home: https://github.com/pyiron/conda_subprocess
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
