{% set name = "conda_subprocess" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/conda_subprocess-{{ version }}.tar.gz
  sha256: d03c6428ea3bde709c5f1fdb0e58bebaa86e1f0e1d1acece1b55d75814c33902

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - conda
    - versioneer
    - pip
  run:
    - python >=3.9
    - conda >=22.9.0,<=24.1.1

test:
  imports:
    - conda_subprocess
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Run a subprocess in a different conda environment.
  home: https://github.com/pyiron/conda_subprocess
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
