{% set name = "conda_subprocess" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/conda_subprocess-{{ version }}.tar.gz
  sha256: 878a97cd65a4329a716aa520f8d92f1c57826472021763d0cd941e6db8874b87

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - conda
    - versioneer
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - conda >=22.9.0,<=25.3.1

test:
  imports:
    - conda_subprocess
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Run a subprocess in a different conda environment.
  home: https://github.com/pyiron/conda_subprocess
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
