schema_version: 1

context:
  name: conda_subprocess
  version: "0.0.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/conda_subprocess-${{ version }}.tar.gz
  sha256: c474b041ea745ff52ab58c904a800b208db13c00a9139268ba70e60cd3aa925d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - conda
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - conda >=22.9.0,<=26.1.0

tests:
  - python:
      imports:
        - conda_subprocess
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Run a subprocess in a different conda environment.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/conda_subprocess

extra:
  recipe-maintainers:
    - jan-janssen
